apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/DevOpsByOmer/StreamCart-Platform.git
    targetRevision: main
    path: GitOps/environments/dev/catalog

  destination:
    server: https://kubernetes.default.svc
    namespace: catalog

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
