apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/DevOpsByOmer/StreamCard-Platform.git
    targetRevision: main
    path: GitOps/environments/dev/payment

  destination:
    server: https://kubernetes.default.svc
    namespace: payment

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
